# Generated by Django 3.1.3 on 2020-11-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_deliveryaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone',
            field=models.CharField(default='0123456789', max_length=11),
            preserve_default=False,
        ),
    ]
