# Generated by Django 3.1.3 on 2020-11-09 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200923_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.FileField(upload_to='image/product')),
                ('sold', models.IntegerField(default=0)),
                ('from_saleprice', models.IntegerField()),
                ('to_saleprice', models.IntegerField()),
                ('comments', models.TextField(max_length=1000)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.types')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='image/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('saleprice', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products')),
            ],
        ),
        migrations.CreateModel(
            name='Amounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.details')),
            ],
        ),
    ]
