# Generated by Django 3.1.3 on 2020-11-26 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='App.products'),
        ),
    ]
