# Generated by Django 3.1.3 on 2020-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_amounts_details_image_products_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='comments',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
