# Generated by Django 3.1.3 on 2020-11-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20201109_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='avatar',
            field=models.FileField(blank=True, default='avatar.jpg', null=True, upload_to='image/product'),
        ),
    ]
