# Generated by Django 3.1.3 on 2020-11-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20201109_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='App.types'),
        ),
    ]
