# Generated by Django 3.1.3 on 2020-11-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20201130_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='describe',
            name='header',
        ),
    ]
