# Generated by Django 3.1.3 on 2020-11-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_describe_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
