# Generated by Django 3.1.3 on 2020-11-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20201111_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounts',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='amounts', to='App.details'),
        ),
    ]
