# Generated by Django 3.1.3 on 2020-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20201130_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
