# Generated by Django 3.1.3 on 2020-12-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20201130_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='detail_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_product', to='App.details'),
        ),
    ]
