# Generated by Django 3.1.3 on 2020-11-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20201112_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
