# Generated by Django 3.1.3 on 2020-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20201202_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Đặt đơn'), (1, 'Chờ xác nhận'), (2, 'Chờ lấy hàng'), (3, 'Đang giao'), (4, 'Đã nhận'), (5, 'Đã hủy'), (6, 'Đã xóa')], default=0),
        ),
    ]
