# Generated by Django 3.1.3 on 2020-12-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20201202_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='detail_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='App.details'),
        ),
    ]
