# Generated by Django 3.1.3 on 2020-12-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20201202_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='detail_product',
            new_name='product_detail',
        ),
    ]
