# Generated by Django 3.1.3 on 2020-11-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='file',
        ),
    ]
