# Generated by Django 3.1.3 on 2020-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20201202_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='on_delete',
            field=models.BooleanField(default=False),
        ),
    ]
