# Generated by Django 3.1.3 on 2020-12-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_types_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='on_delete',
            field=models.BooleanField(default=False),
        ),
    ]
