# Generated by Django 3.1.3 on 2020-12-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_products_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
