# Generated by Django 3.1.3 on 2020-12-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20201211_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='on_delete',
            field=models.BooleanField(default=False),
        ),
    ]
