# Generated by Django 3.1.3 on 2020-12-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_details_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='amounts',
            name='is_plus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amounts',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
