# Generated by Django 3.1.3 on 2021-01-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_auto_20201216_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, '%'), (1, 'vnd')], default=1)),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('max_value', models.IntegerField(blank=True)),
                ('commant', models.CharField(max_length=200)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('on_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='App.products')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='App.promotions')),
            ],
        ),
    ]
