# Generated by Django 3.1.3 on 2020-11-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_auto_20201116_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryaddress', to='App.deliveryaddress'),
        ),
    ]
