# Generated by Django 3.1.3 on 2020-11-19 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_auto_20201116_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='App.deliveryaddress'),
        ),
    ]
