# Generated by Django 3.1.3 on 2021-01-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_auto_20210115_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotions',
            old_name='commant',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='promotionproducts',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='App.types'),
            preserve_default=False,
        ),
    ]
