# Generated by Django 3.1.3 on 2021-01-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_auto_20210115_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionproducts',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='App.products'),
        ),
        migrations.AlterField(
            model_name='promotionproducts',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='App.types'),
        ),
    ]
