# Generated by Django 3.1.3 on 2021-01-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_auto_20210115_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='max_value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
