# Generated by Django 3.1.3 on 2021-01-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_auto_20210116_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionproducts',
            name='type',
        ),
        migrations.CreateModel(
            name='PromotionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotiontype', to='App.promotions')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='App.types')),
            ],
        ),
    ]
