# Generated by Django 3.1.3 on 2021-01-26 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_carts_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='App.promotions'),
        ),
    ]
