# Generated by Django 3.1.1 on 2020-09-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200920_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
