# Generated by Django 3.1.1 on 2020-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200921_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Nam'), (2, 'Nữ'), (0, 'Khác')], default=1, null=True),
        ),
    ]
