# Generated by Django 3.1.1 on 2020-09-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200921_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='avatar',
            field=models.FileField(blank=True, default='avatar.jpg', null=True, upload_to='image/avatar'),
        ),
    ]
